version: "3"
services:
  python-kafka-playhouse:
    image: ${DOCKERTAG:-python-kafka-playhouse}
    build:
      context: .
    depends_on:
      - python-kafka-playhous-migrate
      - database
    volumes:
      - ./src/app:/code/app
    ports:
      - "4000:8000"
    links:
      - database:database
      - kafka:kafka
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  python-kafka-playhous-migrate:
    image: ${DOCKERTAG:-python-kafka-playhouse}
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; python manage.py migrate --noinput'
    depends_on:
      - database
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  database:
    image: postgres:9.6.9
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_CREATE_TOPICS: "products"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_PORT: "9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

