# Generated by Django 3.1.5 on 2021-01-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('slug', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='slug')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
