# Generated by Django 3.1.5 on 2021-01-26 02:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verticals', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verticals.vertical')),
            ],
        ),
    ]
